scss_files:
  - 'app/assets/stylesheets/**'
  - 'client/app/bundles/components/**'
exclude:
  - 'app/assets/stylesheets/application.css'
  - 'vendor/assets/**'
  - 'app/assets/stylesheets/AdminLTE.min.css'
  - 'app/assets/stylesheets/_all-skins.min.css'
  - 'app/assets/stylesheets/blue.min.css'
  - 'app/assets/stylesheets/ionicons.min.css'
  - 'app/assets/stylesheets/custom.css.scss'
  - 'app/assets/stylesheets/footer.css.scss'
linters:
  ImportantRule:
    enabled: false
  MergeableSelector:
    enabled: false
