AddModelVirtualAttributeCheck: { }
AlwaysAddDbIndexCheck: { }
#CheckSaveReturnValueCheck: { }
#CheckDestroyReturnValueCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
#HashSyntaxCheck: { }
IsolateSeedDataCheck: { }
KeepFindersOnTheirOwnModelCheck: { }
LawOfDemeterCheck: { }
#LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 2 }
MoveFinderToNamedScopeCheck: { }
MoveModelLogicIntoModelCheck: { use_count: 4 }
NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
NotUseTimeAgoInWordsCheck: { }
OveruseRouteCustomizationsCheck: { customize_count: 3 }
ProtectMassAssignmentCheck: { }
RemoveEmptyHelpersCheck: { }
#RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: { }
RemoveUnusedMethodsInControllersCheck: { except_methods: [] }
RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }
RemoveUnusedMethodsInModelsCheck: {
  except_methods: [],
  ignored_files: [
    'app/models/course_subject.rb',
    'app/models/user.rb',
    'app/models/supports/static_page.rb',
    'app/models/supports/course_support.rb',
    'app/models/supports/subject_support.rb',
    'app/models/supports/program_support.rb',
    'app/models/ckeditor/attachment_file.rb',
    'app/models/ckeditor/picture.rb',
    'models/serializers/subjects/assignments_serializer.rb',
    'models/serializers/subjects/course_subject_tasks_serializer.rb',
    'models/serializers/subjects/projects_serializer.rb',
    'models/serializers/subjects/subject_details_serializer.rb',
    'models/serializers/subjects/surveys_serializer.rb',
    'models/serializers/subjects/test_rules_serializer.rb',
    'models/serializers/subjects/user_course_tasks_serializer.rb',
    'models/serializers/subjects/user_subjects_serializer.rb',
    'models/serializers/static_pages/static_pages_serializer.rb',
    'models/serializers/support_serializer.rb',
    'models/serializers/support_serializer.rb',
  ]
}
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
ReplaceInstanceVariableWithLocalVariableCheck: { }
RestrictAutoGeneratedRoutesCheck: { }
SimplifyRenderInControllersCheck: { }
SimplifyRenderInViewsCheck: { }
#UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: { }
UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
#UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }
UseQueryAttributeCheck: { }
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }
