all_functions:
  - index
  - show
  - new
  - create
  - edit
  - update
  - destroy
functions:
  - index
  - show
  - create
  - update
  - destroy
during_time:
  course: 60
  project_1: 10
  project_2: 7
  git_tutorial: 2
  mysql: 2
  tutorial_book: 10
  javascript: 4
sql_function_role: "select f.id, f.controller_name, f.action, rf.id as role_func_id from
  functions as f left outer join (select * from role_functions where role_id = $role_id) as rf on f.id = rf.function_id "
