all_functions:
  - index
  - show
  - new
  - create
  - edit
  - update
  - destroy
functions:
  - index
  - show
  - create
  - update
  - destroy
during_time:
  course: 60
  project_1: 10
  project_2: 7
  git_tutorial: 2
  mysql: 2
  tutorial_book: 10
  javascript: 4
